# Generated by Django 4.0.4 on 2022-04-19 20:02

import apps.users.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_email_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.users.managers.UserManagers()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='email_code',
            field=models.CharField(default='000000', max_length=6, verbose_name='Email code'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='Email verified'),
        ),
    ]
