# Generated by Django 4.0.4 on 2022-04-20 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_managers_user_email_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_verified',
        ),
    ]
